train_or_unlearning : retrain
method : boundary_shrink
ATmethod : PGD
unlearn_innerloss : FGSM
unlearn_ATmethod : PGD
data_name : cifar10
model_name : ResNet18
optim_name : sgd
lr : 0.01
epoch : 200
batch_size : 128
forget_class : 0
base_dir : /mnt/server7_hard3/hongsin/Research/ATUnlearning
dataset_dir : /mnt/server7_hard3/hongsin/dataset
checkpoint_dir : /mnt/server7_hard3/hongsin/Research/ATUnlearning/checkpoint
wand : 0
wandb_entity : robust-cil
wandb_project : ATUnlearning
wandb_name : default
wandb_tags : exp




 